blank_issues_enabled: false
contact_links:
  - name: â˜ï¸ Hasura Cloud Help & Support Center
    url: https://cloud.hasura.io/support
    about: For Issues related to Hasura Cloud âš¡ï¸
  - name: â“ Get Support from Discord Community
    url: https://discord.com/invite/hasura
    about: Please ask and answer questions here. ğŸ¥
